### ISSUE TITLE
Avoir les qualificatif de l'air au féminin

### ISSUE THREAD

**Issue by annepoirot** [betagouv/ecosante#11]
Pour le moment les qualificatifs dans les fichiers de sortie csv sont "bon", "moyen" etc
Or dans le mail on parle de qualité de l'air moyenne/bonne etc, donc au féminin...

**Comment by annepoirot** [comment]
Pour le moment j'ai modifié la phrase dan le mail et le sms, donc pas forcément nécessaire. A discuter

**Comment by annepoirot** [comment]
Pour avoir l'échelle:
http://www.atmo-grandest.eu/

**Comment by DavidBruant** [comment]
En suivant la recherche, chuis tombé sur : 
http://www.airparif.asso.fr/reglementation/indice-qualite-air-francais
puis [Arrêté du 22 juillet 2004 relatif aux indices de la qualité de l'air](https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000625624&categorieLien=id) (article 6)
puis https://www.legifrance.gouv.fr/jo_pdf.do?id=JORFTEXT000000625624


![Capture d’écran de 2020-08-13 16-39-18](https://user-images.githubusercontent.com/165829/90148413-96e0f180-dd83-11ea-9947-8cd8ad7ba115.png)
