### ISSUE TITLE
Dans l'outil recommz, avoir un filtre QA mauvaise

### ISSUE THREAD

**Issue by annepoirot** [betagouv/ecosante#12]
Colonne ajoutée au google sheet "recensement des recommandations"

**Comment by annepoirot** [comment]
Il faudrait qu'on ait l'option de choisir:
- Qualité de l'air mauvaise
- Autres recommandations
- Toutes 

Je sais pas trop comment les formuler mais en gros j'aimerais pour masquer de la liste les recommandations liées à la QA mauvaise (ce qui correspond à "autres")

**Comment by annepoirot** [comment]
Et peut-être pareil pour "Allergie", vu qu'on a pas les données j'aimerais pouvoir filtrer les recommandations liées aux pollens

**Comment by DavidBruant** [comment]
J'avais oublié les allergies
