### ISSUE TITLE
[site] créer une page de confirmation pour le mail sur le changement de fréquence

### ISSUE THREAD

**Issue by annepoirot** [betagouv/ecosante#162]
L'objectif est de créer une page de confirmation suite au bouton présent dans le mail sendinblue (https://my.sendinblue.com/rnb/index/id/406)

Contenu de la page : https://pad.incubateur.net/yjbiySSORnOPtj6VyqBpkQ

On doit pouvoir récupérer les mails des personnes qui ont cliqué pour ensuite pouvoir modifier leur profil.

**Comment by l-vincent-l** [comment]
Je me demande si ça ne devrait pas être la même page que pour la confirmation de changement par SMS

**Comment by annepoirot** [comment]
Oui je pense !
