### ISSUE TITLE
La région et l'AASQA pour certaines villes ne fonctionnent pas dans l'outil csv

### ISSUE THREAD

**Issue by annepoirot** [betagouv/ecosante#22]
Charmant, Saint martin la pallu, auxerre, vesoul, Guilherand-Granges, Brange

**Comment by DavidBruant** [comment]
**Charmant** est [devenu](https://fr.wikipedia.org/wiki/Charmant) la commune de **Boisné-La Tude**

**Guilherand-Granges** va faire l'objet d'un travail spécifique : https://github.com/betagouv/indice_pollution/issues/14

Je ne vois plus de problème avec **Saint-Martin-la-Pallu** (?)
Je ne vois plus de problème avec **auxerre** et **vesoul**. Ça a été corrigé, en rajoutant la Région BFC, j'imagine

J'ai découvert les problèmes suivants : 
**Biscarosse** s'écrit [officiellement](https://fr.wikipedia.org/wiki/Biscarrosse) avec 2 *r* : **Biscarrosse**
**Isss-les-Moulineaux**. J'imagine qu'il s'agit d'**Issy-les-Moulineaux**
**Loc Maria Grand Champ** s'écrit plutôt **Locmaria Grand Champ**

Pour les villes mal orthographiées, une solution à court terme, ça serait de corriger les réponses des personnes. Soit directement dans nextcould form, soit dans le code

**Comment by annepoirot** [comment]
Pour Biscarrosse et Issy les moulineaux et locmaria j'ai changé dans le form nextcloud !

**Comment by annepoirot** [comment]
Pour Boisné-La Tude, le lien AASQA fonctionne mais pas la QA (alors que pour une autre ville de la même AASQA, Nouvelle Aquitaine, ça fonctionne)

**Comment by annepoirot** [comment]
Pareil pour Cenon, il semblerait que ce soit Nouvelle Aquitaine

**Comment by DavidBruant** [comment]
> Pareil pour Cenon, il semblerait que ce soit Nouvelle Aquitaine

> Sisyphe est surtout connu pour son châtiment, consistant à pousser une pierre au sommet d'une montagne, d'où elle finit toujours par retomber.

https://fr.wikipedia.org/wiki/Sisyphe
