### ISSUE TITLE
[outil recomz] quand on actualise le tableau google sheet, ça n'actualise pas l'outil

### ISSUE THREAD

**Issue by annepoirot** [betagouv/ecosante#25]

**Comment by DavidBruant** [comment]
ah bah, j'avais hardcodé le csv 
https://github.com/betagouv/ecosante/blob/bc67277815c670189985f882c8da94844003854c/assets/js/recommz.js#L244
:facepalm:

**Comment by DavidBruant** [comment]
Avec ce lien, ça va être mieux : https://docs.google.com/spreadsheets/d/e/2PACX-1vQ8zyNiyCfwGRgo9qMrufVujrlVsf-DlYACQAaXrulKdTnfjIwxEQXAqhMKkrjVO0P_BalC3iI1JZaf/pub?gid=1814050928&single=true&output=csv

**Comment by annepoirot** [comment]
Yes je veux bienque tu me montres comment faire parce qu'on actualise souvent, même pour les fautes etc. Merci !
