### ISSUE TITLE
Les colonnes de fichier de sortie ne sont pas celles attendues

### ISSUE THREAD

**Issue by annepoirot** [betagouv/ecosante#4]
Colonnes attendues : 
Mail | Région | Ville | Lien_Boutton | Indice_ATMO | Qualité_Air | Pathologie_respiratoire | Allergies | Activité_sportive | Cycliste | Automobiliste | Fumeur | Format | Téléphone | Fréquence | Recommandation | Explication |

**Comment by DavidBruant** [comment]
L'outil ressort désormais un csv avec les bonnes colonnes avec 2 exceptions : 
- `Lien_Boutton` : j'ai besoin de mieux comprendre le process de création de ce lien
- `Indice_ATMO`: est-ce qu'il est nécessaire au final ?

**Comment by annepoirot** [comment]
On peut enlever Indice_ATMO. 
Lien_Boutton : c'est le lien vers le site de l'AASQA de la région de l'utilisateur. Parfois on peut avoir un lien vers le ville exacte, parfois non car le lien reste stable.
