### ISSUE TITLE
La qualité de l'air n'est pas rempli automatiquement pour certaines villes

### ISSUE THREAD

**Issue by annepoirot** [betagouv/ecosante#5]
Montpellier
Paris
Mery-sur-Oise
Epinal
Issy-les-Moulineaux
Fontenay-sous-Bois
Boulogne
Strasbourg
Lille
Meudon
Hénin-Beaumont
Livry-Gargan
Poissy
Vesoul
Guilherand-Granges
Saint-Affrique
Brenouille
Auxerre
Toulon
Wiesviller
Biscarrosse
Le Plessis-Pâté
St martin la pallu
Bar
Nice
val de la haye
Carcans
PETIT MESNIL
JOINVILLE LE PONT
cenon
Bardos
Conty
NOMPATELIZE
locmaria grand champ
Branges
saillans
ASNIERES SUR OISE
QUINCY

**Comment by DavidBruant** [comment]
J'ai l'impression qu'on a tout sauf l'ïle-De-France actuellement
Je ne sais pas comment régléer l''ile-de-France d'ici lundi
À la prochaine plannif, on peut ptèt créer une issue dédiée à l'IDF et fermer celle-ci

**Comment by annepoirot** [comment]
Ok! J'ai contacté un mec de Airparif par mail, mais il ne rentre que le 24 août...

**Comment by annepoirot** [comment]
J'ai fais une demande de clef API :
Veuillez trouver ci-dessous les liens de téléchargements des notices associées
https://www.dropbox.com/s/64q68sj03x8o17m/API%20WMS_Cartes_Temps_R%C3%A9el.pdf?dl=0
https://www.dropbox.com/s/jsodakx7f8s1c57/API_Indices_alertes.pdf?dl=0
https://www.dropbox.com/s/bq2vy7mj6b3pwbe/API_WPS_cartes_Temps_R%C3%A9el.pdf?dl=0


Veuillez trouver ci-dessous les liens pour télécharger les fichiers json pour une documentation Postman :
https://www.dropbox.com/s/qwgcffaz19zzvu9/APIs%20Airparif%20-%20cartographie%20et%20donn%C3%A9es%20temps%20r%C3%A9el.postman_collection.json?dl=0
https://www.dropbox.com/s/ut1hk46593sbsch/APIs%20Airparif%20-%20indice%20-%20alerte.postman_collection.json?dl=0

**Comment by DavidBruant** [comment]
Chuis pas sûr, mais jpense qu'il manque aussi la Normandie

**Comment by annepoirot** [comment]
Il manque toujours 
- toutes les villes d'IDF
- Auvergne : Guilherand-Granges
- Nouvelle aquitaine: Charmant, parce que la ville n'st pas trouvable sur le site de la Nouvelle Aquitaine, le code INSEE de la ville est 16082, c'est très proche d'Angoulême donc possibilité de mettre ce code INSEE ?), Saint martin la pallu, Bados, Carcans, Cenon
- BFC (Vesoul, Auxerre)
