### ISSUE TITLE
Envoi automatisés par API sendinblue

### ISSUE THREAD

**Issue by DavidBruant** [betagouv/ecosante#54]
Référence : https://developers.sendinblue.com/reference

Sendinblue nous apporte quelque trucs facilement, alors pour une première version, on va coder avec l'API exactement les actions qui sont faites manuellement

## Créer une liste de contacts

Pour créer une liste en important des contacts depuis un csv : https://developers.sendinblue.com/reference#importcontacts-1
avec le corps `{newList: {listName, folderId}, fileBody, updateExistingContacts: true}`
Pour le `listName` : `2020-08-12-Tous-les-jours-Mail` (et variations sur dates, fréquence et canal)

Pour créer une liste, il faut un `folderId`. Apparemment, actuellement, on créé les listes dans un *folder* par défaut. On peut retrouver l'id grâce à : https://developers.sendinblue.com/reference#getfolders-1 (lister tous les dossiers)

`fileBody` est exactement le csv qu'on génère actuellement

`updateExistingContacts: true`, c'est pour matcher avec l'actuel "Cocher "Mettre à jour les attributs des contacts existants" si ce n'est pas déjà fait par défaut"

Ptèt `notifyUrl` pour être prévenu.e.s de quand ça se termine

On récupère un `listId` en retour

## Créer une campagne email

Il y a déjà une campagne. Et on la met à jour tous les jours

On peut trouver l'id de la campagne en jouant avec https://developers.sendinblue.com/reference#getemailcampaigns-1

Et une fois qu'on a l'id, on peut l'update avec https://developers.sendinblue.com/reference#updateemailcampaign et la `listId` créée plus haut dans le champ `recipients.listIds`

À partir de l'id de la campagne, on peut envoyer avec : https://developers.sendinblue.com/reference#sendemailcampaignnow-1

## sms

C'est la même chorégraphie que pour les emals, mais avec des endpoints dédiés aux emails

**Comment by DavidBruant** [comment]
Référence : https://developers.sendinblue.com/reference

Sendinblue nous apporte quelque trucs facilement, alors pour une première version, on va coder avec l'API exactement les actions qui sont faites manuellement

Pour créer une liste : https://developers.sendinblue.com/reference#createlist-1
Pour créer une liste, il faut un `folderId`

Apparemment, actuellement, on créé les listes dans un dossier par défaut. On peut retrouver l'id grâce à : https://developers.sendinblue.com/reference#getfolders-1 (lister tous les dossiers)

(je vais éditer ce commentaire pour compléter)

**Comment by DavidBruant** [comment]
Étant donné que les csv générés possèdent mal la qualité de l'air, ce qu'on va faire, c'est créer une autre zone dans l'outil-csv (ou un autre outil) dédiée à l'envoi
Dans cette zone, on réupload les fichiers csv complétés et prêts à l'emploi

**Comment by DavidBruant** [comment]
https://developers.sendinblue.com/docs/faq#how-can-i-test-the-api

> You can test our API directly in the reference section. Just enter your API-Key and your parameters.
> ❗️ It's not a sandbox. All the calls will be reflected in your account and credits will be deducted in case of billing events (e.g.: email sending).

donc pour le test, je vais me créer des fausses listes de 1 personne avec mon adresse email

**Comment by DavidBruant** [comment]
Dans une branche, je publie mon avancée : https://github.com/betagouv/ecosante/blob/issue-54/tools/sendinblueAPIPlayground.py

**Comment by DavidBruant** [comment]
En travaillant sur l'import de contacts, je comprends que :
- `https://api.sendinblue.com/v3/contacts/import` ne peut que retourner un `202 Accepted`
- donc pour recevoir l'id de la liste, il faut utiliser le paramètre `notifyURL`
- donc il faut un serveur, exposé à internet qui écoute les requêtes `POST` envoyée à `notifyURL`

**Comment by annepoirot** [comment]
# Objectif : comment faire pour automatiser vite et simple ? 

Priorité : ne pas envoyer de choses fausses

## Process

Envoi de la newsletter à 7h 

## Bug d'indice ATMO

Si l'indice ATMO n'est pas récupérable dans une région car bug. 

Alors on n'envoie pas la newsletter pour cette région. 

## Sur les recommandations

Pour les recommandations qui ne sont pas associées à des données utilisateurs => on les met inutilisable pour l'instant.
