### ISSUE TITLE
Avoir 4 csv en fonction de la fréquence et du format d'envoi

### ISSUE THREAD

**Issue by annepoirot** [betagouv/ecosante#7]
1) Mail et tous les jours
2) Mail et QA mauvaise
3) SMS et tous les jours
4) SMS et QA mauvaise

**Comment by DavidBruant** [comment]
Si le format et la fréquence sont dans le titre du fichier, on les vire du contenu du fichier ?

**Comment by annepoirot** [comment]
Oui on peut !

**Comment by DavidBruant** [comment]
Je vais en profiter pour rajouter la date dans le nom des fichiers

**Comment by DavidBruant** [comment]
Bim bam boum, jpense que c'est bon
Je te laisse valider @annepoirot, me dire si ça fait bien ce que tu veux

**Comment by annepoirot** [comment]
Ca ne fonctionne pas de mon côté, aucun fichier de sortie quand j'upload le csv... c'est bien ce lien ? https://betagouv.github.io/ecosante/outil-csv.html

**Comment by DavidBruant** [comment]
Yes, c'est le bon lien
Ça marche de mon côté
Parfois, il est nécessaire d'attendre ~1 minute avant d'avoir un retour

Si c'est très relou, je te propose de faire une nouvelle issue pour demander un "spinner". Si c'est pas très relou, je peux soit rien faire, soit mettre un message de rappel
